### ISSUE TITLE
None of the codes provided in README.md work

### ISSUE THREAD

**Issue by sapientiam-congnitio** [optimization-for-data-driven-science/FERMI#1]
```
from FERMI import AdultDataset
from FERMI import FERMIBinary

AdultDataset.download_data()
X_train, S_train, Y_train = AdultDataset.read_binary_adult(mode='train')
X_test, S_test, Y_test = AdultDataset.read_binary_adult(mode='test')


fermi_instance = FERMIBinary.FERMI(X_train, X_test, Y_train, Y_test, S_train, S_test)
FERMIBinary.FERMI_Logistic_Regression(fermi_instance, is_missing=True)
```
Got an error TypeError: FERMI_Logistic_Regression() got an unexpected keyword argument 'is_missing'. Could please explain what might be the error?

**Comment by sinaBaharlouei** [comment]
Could you please provide which dataset did you use? Does it contain missing values in the sensitive attribute? Or the entire dataset? The method can handle missing values only if they are in the sensitive attribute. If not, you should first impute the data.

**Comment by sapientiam-congnitio** [comment]
Hmm. I didn't quite understand what you mean? I thought that the code above is a dataset and it already includes sensitive features, thus I just wanted simply to run it to familiarize myself. Also I am trying to rerun your Toxic_Comment.ipynb but there are variables that are not defined in the notebook (e.g. X_S, S, and self.P_s_sqrt_inv).

**Comment by sapientiam-congnitio** [comment]
Hi. Sorry for bothering you, I tried to do some magic with your .ipynb file but the results with and without regularizer are pretty much the same. And I am still not able to understand how you ran your .pynb with not defined variables.

**Comment by sinaBaharlouei** [comment]
Hello again. I uploaded a file [BinaryFERMI.ipynb](https://github.com/optimization-for-data-driven-science/FERMI/blob/master/BinaryFERMI.ipynb) that can be run on the Adult dataset (see the dataset folder for the data). If you want to run the code as a package, first you must install it via

```
pip install FERMI-ODDS
```

Otherwise, the codes might not work properly. But for quick access, I recommend [BinaryFERMI.ipynb](https://github.com/optimization-for-data-driven-science/FERMI/blob/master/BinaryFERMI.ipynb) file. Let me know if you can run it properly.

**Comment by sapientiam-congnitio** [comment]
Thanks a lot. Could you please have a look at Toxic_Comment.ipynb and have a look at the place where you call regularizer function and pass X_S and S variables to it, they are not defined in the notebook? I defined S based on your equation in the paper but I would like to know why you haven't defined S and it still works. Thank you in advance.

**Comment by sapientiam-congnitio** [comment]
Thanks a lot. Could you please have a look at Toxic_Comment.ipynb and have a look at the place where you call regularizer function and pass X_S and S variables to it, they are not defined in the notebook? I defined S based on your equation in the paper but I would like to know why you haven't defined S and it still works. Thank you in advance.

**Comment by sapientiam-congnitio** [comment]
Thanks a lot. Could you please have a look at Toxic_Comment.ipynb and have a look at the place where you call regularizer function and pass X_S and S variables to it, they are not defined in the notebook? I defined S based on your equation in the paper but I would like to know why you haven't defined S and it still works. Thank you in advance.

**Comment by sapientiam-congnitio** [comment]
Thanks a lot. Could you please have a look at Toxic_Comment.ipynb and have a look at the place where you call regularizer function and pass X_S and S variables to it, they are not defined in the notebook? I defined S based on your equation in the paper but I would like to know why you haven't defined S and it still works. Thank you in advance.
